name: Deploy Flask App

on:
  push:
    branches:
      - main  # yaa jo bhi branch aap use kar rahe hain

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Aapke Flask app ke liye required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask requests

    - name: Run Flask app
      run: |
        nohup python app.py &
